### PR TITLE
NA-800 further updates

### PR DESCRIPTION
**Pull request by nhsbsa-jamcn**
- Removed unrequired views.
- Moved 'Add new staff member' button to top of staff list view.
- Made staff filter display toggleable.
- Made staff select checkboxes bigger. 
- Replaced 'Select All/None' buttons with a single 'Select All/None' column header.
- Changed staff count to list staff members to be affected by a bulk action instead.
- Changed demo users to be more generic.
- Removed end date from status fields. 
 - Hid fields not intended for bulk edits.
- Added functionality for selecting streams from searchable dropdown.

### CODE REVIEW

**Comment by BillRobo5** [comment]
**Stream Selection.**

We've missed something with the new stream selection process; how do we remove an existing stream?

The list to select stream from contains all stream categories which they've previously mentioned makes it difficult to find the specific stream if its far down the list.  I'd like to discuss this at statnd-up


**Filter**

Filter not expanding for me in Edge and Chrome.

**Comment by nhsbsa-jamcn** [comment]
> We've missed something with the new stream selection process; how do we remove an existing stream?

Assuming we're talking about 'assigned streams'; when the assigned streams are added below, there's a remove link which unassigns it.  In the final platform it would show previously assigned streams in that area (doesn't work in the prototype).

> The list to select stream from contains all stream categories which they've previously mentioned makes it difficult to find the specific stream if its far down the list. I'd like to discuss this at statnd-up

I don't know if you've noticed but the drop down box is searchable (its the same as the job title drop down), so you just start typing what you're looking for and it'll filter down.

> Filter not expanding for me in Edge and Chrome.

I've tested in Edge, FF and Chrome - its working in all for me. Could you open the debug console and try it to see if there's any useful errors that'll point out whats happening?


I've double checked, everything is checked in so our code-bases are the same meaning there's something environmental causing these discrepancies.  Could you clear your cache and try running in a new session/private window and see if it behaves the same for you?

**Comment by BillRobo5** [comment]
Agree with comments re stream selection and  removal.   Still have issues with the filter not using the latest code locally.  Happy for you to merge and deploy however as that may fix

**Review by BillRobo5 — APPROVED** [review]
looks good

**Pull request merged**
